# -*- mode: ruby -*-
# vi: set ft=ruby :

# See README.md for details

VAGRANTFILE_API_VERSION = '2'.freeze

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.define 'wikitest' do |wikitest|
    wikitest.vm.hostname = 'wikitest'

    wikitest.vm.network 'private_network', ip: '172.31.0.203'
  end

  config.vm.provider :virtualbox do |p|
    p.customize ['modifyvm', :id, '--memory', 2048]
  end

  config.vm.provision :shell, path: '../install_agent.sh'

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = './../environment/manifests'
    puppet.module_path = './../environment/modules'
  end

  config.vm.provision 'puppet_server' do |puppet|
    puppet.puppet_server = 'puppetmaster'
    puppet.options = '-w 30' # wait for cron job to sign cert
  end
end
