# -*- mode: ruby -*-
# vi: set ft=ruby :

# See README.md for details

VAGRANTFILE_API_VERSION = '2'.freeze
COOKBOOKS_PATH = './../cookbooks/'.freeze

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.define 'wikitest' do |wikitest|
    wikitest.vm.hostname = 'wikitest'

    wikitest.vm.network 'private_network', ip: '172.31.0.203'
  end

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "#{COOKBOOKS_PATH}/puppetmaster/Berksfile"

  config.vm.provider :virtualbox do |p|
    p.customize ['modifyvm', :id, '--memory', 2048]
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = COOKBOOKS_PATH

    chef.run_list = [
      'recipe[puppetmaster::agent]'
    ]
  end

  config.vm.provision 'puppet_server' do |puppet|
    puppet.puppet_server = 'puppetmaster'
  end
end
