# -*- mode: ruby -*-
# vi: set ft=ruby :

# See README.md for details

VAGRANTFILE_API_VERSION = '2'.freeze

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'centos/7'

  config.vm.define 'wiki' do |wiki|
    wiki.vm.hostname = 'wiki'

    wiki.vm.network 'private_network', ip: '172.31.0.202'
  end

  config.vm.provision :shell, path: '../install_agent.sh'

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = './../environment/manifests'
    puppet.module_path = './../environment/modules'
  end

  config.vm.provision 'puppet_server' do |puppet|
    puppet.puppet_server = 'puppetmaster'
  end
end
