# -*- mode: ruby -*-
# vi: set ft=ruby :

# See README.md for details

VAGRANTFILE_API_VERSION = '2'.freeze
COOKBOOKS_PATH = './../cookbooks/'.freeze

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'centos/7'

  config.vm.define 'puppetmaster' do |puppetmaster|
    puppetmaster.vm.hostname = 'puppetmaster'

    puppetmaster.vm.network 'private_network', ip: '172.31.0.201'
  end

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "#{COOKBOOKS_PATH}/puppetmaster/Berksfile"

  config.vm.provider :virtualbox do |p|
    p.customize ['modifyvm', :id, '--memory', 3072]
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = COOKBOOKS_PATH

    chef.run_list = [
      'recipe[puppetmaster]'
    ]
  end
end
